### ISSUE TITLE
Add a `volume` property to stations

### ISSUE THREAD

**Issue by nightsh** [rootio/rootio_web#143]
As per @judelove's email:

> Also, can you add a volume field (int, range 1-15) on station attributes so
that the volume can be adjusted remotely via sync. I notice that different
phones have varying audio level outputs and a setting of 10 may be quiet on
one but loud on the other

**Comment by judelove** [comment]
I do not see this change on the server...

**Comment by nightsh** [comment]
I still have to deploy the latest changes

**Comment by judelove** [comment]
I just scanned throuh the API endpoint on github and there is no volume attribute in the station information.  Can you add a JSON attribute named 'media_volume' to the 'station/<int:id>/information' endpoint?
