### ISSUE TITLE
Radio dashboard is slow

### ISSUE THREAD

**Issue by nightsh** [rootio/rootio_web#157]
It takes too long to get into the status page. We probably need to optimize some queries?

**Comment by csik** [comment]
Took 17 seconds to load this morning...

**Comment by judelove** [comment]
Hey,

Yes - The first time you load this page, it takes a while to load. I have
yet to nail down if this is after a web server restart, browser cookie
clearing, re-login or something else. And this is true for any other page
other than the status page. But subsequent reloads of this page are now
within 3 seconds unlike in the past where this was consistently close to 20
seconds.  Also, that lo

I will close this and reopen it as a separate issue to look at instances
that lead to this sporadic occurrence.

Jude
