### ISSUE TITLE
Really switch to AWS.

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#165]
Yes. Switch the storage to AWS for services and web.

**Comment by judelove** [comment]
Mounted S3 as storage. Performance is slower than local disk but should be acceptable. Next step is to integrate using boto

**Comment by nightsh** [comment]
I tried it locally before, same conclusion, slower. Boto3 is still the way to go, I'll create an issue to continue integration at telephony level (web UI is S3-ready as far as I remember, only station runner & friends cannot play from remote URIs yet).

Thanks for doing this tho, I kept having second thoughts about it and ended up not doing anything.

**Comment by nightsh** [comment]
Opened #214
