### ISSUE TITLE
Revisit sync of music files

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#182]
This is a leading cause of server downtime, music file sync should be treated aynchronously

**Comment by nightsh** [comment]
FYI, the commit introducing the function decorated with `@app.before_first_request`in `app.py` hangs my dev server. No phone / station connected, no FS running, no services, just the web interface. Hadn't had time to debug yet, but it's definitely something in `handle_file` function / the `while True` loop (commented it out and everything is back up).
