### ISSUE TITLE
Reset modal popups on dismiss

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#200]
each time the modal displays are discarded (Podcasts, add location, add telephone, scheduling) reset the hidden form to avoid validation errors and the likes.

**Comment by nightsh** [comment]
But that would also clear unwanted values, such as station id on recurring form or the CSRF tokens, rendering the modal form unusable for subsequent submits.

Won't fix, as it might break stuff. We need to manually clear whichever inputs we want instead of group clearing everything.
