### ISSUE TITLE
Schedule home page is very slow to load

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#220]

**Comment by nightsh** [comment]
This is the culprit:

```
            <td>{{ station.successful_scheduled_programs()|length }} successful, {{ station.unsuccessful_scheduled_programs()|length }} failed, {{ station.scheduled_programs()|length }} Scheduled</td>

```

So those aggregations kill the performance. We need to implement an alternate way of dealing with them.

**Comment by carlosmouracorreia** [comment]
@judelove added this code with hope of making it faster.
https://gist.github.com/hest/8798884

**Comment by carlosmouracorreia** [comment]
It actually worked (Did it for nr of scheduled programs, failed and successful played ones)
