### ISSUE TITLE
"Browse" option for uploading file into track throws validator error even when file is MP3 or WAV

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#387]

**Comment by carlosmouracorreia** [comment]
Is this for staging? What browser are you using? I've used Safari and Chrome for both staging and prod and worked just fine. (used the attached file info)
https://staging.rootio.eu/content/tracks/64/files/add
<img width="242" alt="image" src="https://user-images.githubusercontent.com/6900758/70539548-c5a32a00-1b5b-11ea-89a0-fc32dc7ff6f0.png">

**Comment by carlosmouracorreia** [comment]
This is not happening for me @judelove . please let me know if it happens still.

**Comment by carlosmouracorreia** [comment]
Recheck if validation goes down to the file header (not the extension)

**Comment by carlosmouracorreia** [comment]
This is now confirmed as working (by file extension). To go as deep as the file header some hours of work might be needed, not sure if this is a priority. Closing for now
