### ISSUE TITLE
Authorization validation

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#62]
different parts of the site require varying levels of authorization. Verify that no URLs are actionable without required authorization (both web and REST API)

**Comment by nightsh** [comment]
I think these things are already testable as they are, by interpreting the HTTP status of each page / API endpoint.
I see we already have [some testing capabilities](https://github.com/rootio/rootio_web/blob/master/docs/testing.md) – are there any hard rules to follow regarding it, or I can, let's say, change the test runner to [tox](https://tox.readthedocs.io/en/latest/) if I find it works better for us?

**Comment by nightsh** [comment]
Blocked by #113
