### ISSUE TITLE
Add TTS configuration to station

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#63]
Add TTS configuration (accent, gender, Language, audio format, sample rate) should be doable at a program level in the future. Ideally this should be a page in a new sub-menu 'Configuration (or settings)'

**Comment by Luthieneye** [comment]
User scenarios for TTS

Local buy and sell ads - Listeners from the community can use text messaging to place adverts on the radio. TTS will be used to read out the adverts. This can be a potential source of income for the community radio stations.

Song dedications - Listeners can use text messages to request dedications. TTS will be used to read out the dedications.

Municipal Facebook/Twitter announcements - Audio programs can be automatically created from local government social media platforms such as Facebook and Twitter. We are currently exploring this with the content supported through the Município de Porto Moniz Facebook page at https://pt-br.facebook.com/portomoniz.pt/.

Structured input - Information from trusted sources in a predefined format can be read out. For example a local weather station can set up an RSS feed to be played after news segments. We are currently exploring this with the content supported through Bere Island’s new feed (http://www.bereisland.net/news-2018/news/), and a potential partnership with geo-spatial.org for presenting up-to-the-minute weather information in Romania.

**Comment by Luthieneye** [comment]
Level of effort?

Does this task need to be broken down?
