### ISSUE TITLE
Create email accounts for rootio_web instances

### ISSUE THREAD

**Issue by nightsh** [rootio/rootio_web#69]
We need to use separate accounts for production, staging and (maybe) development.

I would go with:
* prod: radio@rootio.org
* staging: staging@rootio.org
* dev: dev@rootio.org

The `dev` email would likely be used in all kinds of development related tasks, so it'd be nice to have it on a different IP or domain name, but it's not a deal breaker.

Thanks! :beers:

**Comment by csik** [comment]
This had already been done. I think "radio" is confusing, we discussed "live," I went with "production." Open a separate issue for dev if you wish but RootIO would purchase and I would point the name...

➜  ~ nslookup production.rootio.org
Server:		2001:8a0:6050:ef01:3291:8fff:fe46:253a
Address:	2001:8a0:6050:ef01:3291:8fff:fe46:253a#53
Non-authoritative answer:
Name:	production.rootio.org
Address: 165.227.153.91

➜  ~ nslookup staging.rootio.org
Server:		2001:8a0:6050:ef01:3291:8fff:fe46:253a
Address:	2001:8a0:6050:ef01:3291:8fff:fe46:253a#53
Non-authoritative answer:
Name:	staging.rootio.org
Address: 159.65.194.149

**Comment by nightsh** [comment]
@csik the issue was mainly about the email accounts used by the Flask app, and barely touching on the deployment targets. Are those addresses set up as well?

**Comment by csik** [comment]
No, I didn't know the context. I'm not an active developer on the project so you probably shouldn't assign me things.

**Comment by nightsh** [comment]
Update following #92 - let's add a SES powered `noreply@rootio.org` account which we'd only use for sending stuff from. We could add a `Reply-To` header for emails we want replies to, but that's probably not going to be the case anytime soon.

Cc @judelove
